version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-app:latest
    container_name: app
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    networks:
      - patrik

  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
        - pg-data:/var/lib/postgresql/test/data
    networks:
      - patrik


  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/testPatrik12!
    networks:
      - patrik

networks:
  patrik:

volumes:
  pg-data: